{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Sur le cloud (avec Google Dataproc + Storage).\n",
    "\n",
    "### 1. Importation des librairies."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "from PIL import Image\n",
    "import numpy as np\n",
    "import io\n",
    "\n",
    "from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, adjusted_rand_score\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "\n",
    "from tensorflow.keras.applications.mobilenet_v2 import MobileNetV2, preprocess_input\n",
    "from tensorflow.keras.preprocessing.image import load_img, img_to_array\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense, GlobalAveragePooling2D\n",
    "from tensorflow.keras.utils import to_categorical, set_random_seed\n",
    "from tensorflow.keras.optimizers import Nadam\n",
    "from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping\n",
    "\n",
    "from pyspark.sql.functions import col, udf, element_at, split\n",
    "from pyspark.sql.types import ArrayType, FloatType\n",
    "from pyspark.sql import SparkSession"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 2. Démarrage d'une sessions spark.\n",
    "\n",
    "**yarn** est le gestionnaire par défaut du cluster, il n'est donc pas nécessaire de le préciser."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Setting default log level to \"WARN\".\n",
      "To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).\n",
      "24/09/27 19:27:29 INFO SparkEnv: Registering MapOutputTracker\n",
      "24/09/27 19:27:29 INFO SparkEnv: Registering BlockManagerMaster\n",
      "24/09/27 19:27:29 INFO SparkEnv: Registering BlockManagerMasterHeartbeat\n",
      "24/09/27 19:27:29 INFO SparkEnv: Registering OutputCommitCoordinator\n"
     ]
    }
   ],
   "source": [
    "# Démarrage d'une session Spark\n",
    "spark = (SparkSession.builder\n",
    "                     .appName('P8')\n",
    "                     .getOrCreate())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "sc = spark.sparkContext"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "            <div>\n",
       "                <p><b>SparkSession - hive</b></p>\n",
       "                \n",
       "        <div>\n",
       "            <p><b>SparkContext</b></p>\n",
       "\n",
       "            <p><a href=\"http://cluster-p8-m.europe-west1-b.c.eloquent-branch-436714-u0.internal:36213\">Spark UI</a></p>\n",
       "\n",
       "            <dl>\n",
       "              <dt>Version</dt>\n",
       "                <dd><code>v3.5.1</code></dd>\n",
       "              <dt>Master</dt>\n",
       "                <dd><code>yarn</code></dd>\n",
       "              <dt>AppName</dt>\n",
       "                <dd><code>P8</code></dd>\n",
       "            </dl>\n",
       "        </div>\n",
       "        \n",
       "            </div>\n",
       "        "
      ],
      "text/plain": [
       "<pyspark.sql.session.SparkSession at 0x7fd3d40e0850>"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "spark"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Entraînement du modèle avec un échantillon de trois classes."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_dir = 'gs://chakir-p8/data/train_local'\n",
    "test_dir = 'gs://chakir-p8/data/test_local'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_model(base_model, nbr_de_classes):\n",
    "    for layer in base_model.layers:\n",
    "        layer.trainable = False\n",
    "    # Ajout des couches de classification\n",
    "    model = Sequential([base_model,\n",
    "                        GlobalAveragePooling2D(),\n",
    "                        Dense(1024, activation='relu'),\n",
    "                        Dense(nbr_de_classes, activation='softmax')\n",
    "                       ])\n",
    "    return model"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {},
   "outputs": [],
   "source": [
    "def metrics_display(true_labels, predicted_labels):\n",
    "    accuracy = accuracy_score(true_labels, predicted_labels)\n",
    "    precision = precision_score(true_labels, predicted_labels, average='macro')\n",
    "    recall = recall_score(true_labels, predicted_labels, average='macro')\n",
    "    f1 = f1_score(true_labels, predicted_labels, average='macro')\n",
    "    ARI = adjusted_rand_score(true_labels, predicted_labels)\n",
    "    print(f'accuracy = {accuracy}   precision = {precision}   recall={recall}   f1 = {f1}   ARI = {ARI}')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fonction pour obtenir les chemins des images et leurs étiquettes\n",
    "def get_image_paths_and_labels(spark_session, dir_path):\n",
    "    \n",
    "    images = (spark_session.read.format('binaryFile')\n",
    "                           .option('pathGlobFilter', '*.jpg')\n",
    "                           .option('recursiveFileLookup', 'true')\n",
    "                           .load(dir_path))\n",
    "\n",
    "    images = images.withColumn('label', element_at(split(images['path'], '/'),-2))\n",
    "    \n",
    "    return images"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Fonction pour prétraiter une image\n",
    "def preprocess_image(binary_image):\n",
    "    image = Image.open(io.BytesIO(binary_image))\n",
    "    image = image.resize((224, 224))\n",
    "    img_array = img_to_array(image)\n",
    "    img_array = preprocess_input(img_array)\n",
    "    return img_array.flatten().tolist()\n",
    "    \n",
    "# Création d'une UDF pour prétraiter les images\n",
    "preprocess_image_udf = udf(preprocess_image, ArrayType(FloatType()))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_and_test_model_spark(train_dir, \n",
    "                               test_dir, \n",
    "                               model,\n",
    "                               spark_session,\n",
    "                               seed_value=42, \n",
    "                               target_size=(224, 224), \n",
    "                               optimizer=Nadam, \n",
    "                               learning_rate=0.001, \n",
    "                               epochs=10):\n",
    "    \n",
    "    # Fixation des germes pour la reproductibilité des résultats\n",
    "    set_random_seed(seed_value)\n",
    "    \n",
    "    # Obtention des chemins des images et leurs étiquettes\n",
    "    train_df = get_image_paths_and_labels(spark_session, train_dir)\n",
    "    test_df = get_image_paths_and_labels(spark_session, test_dir)\n",
    "\n",
    "    # Prétraitement des images\n",
    "    train_df = train_df.withColumn('preprocessed_image', preprocess_image_udf(col('content')))\n",
    "    test_df = test_df.withColumn('preprocessed_image', preprocess_image_udf(col('content')))\n",
    "\n",
    "    # Conversion en format numpy pour le modèle tensorflow\n",
    "    train_data = train_df.select('preprocessed_image', 'label').collect()\n",
    "    test_data = test_df.select('preprocessed_image', 'label').collect()\n",
    "\n",
    "    X_train = np.array([np.array(row['preprocessed_image']).reshape(224, 224, 3) for row in train_data])\n",
    "    X_test = np.array([np.array(row['preprocessed_image']).reshape(224, 224, 3) for row in test_data])\n",
    "\n",
    "    y_train = np.array([row['label'] for row in train_data])\n",
    "    y_test = np.array([row['label'] for row in test_data])\n",
    "\n",
    "    # Encodage des étiquettes en one-hot\n",
    "    encoder = LabelEncoder()\n",
    "    y_train = encoder.fit_transform(y_train)\n",
    "    y_test = encoder.transform(y_test)\n",
    "    y_train_cnn = to_categorical(y_train)\n",
    "    y_test_cnn = to_categorical(y_test)\n",
    "\n",
    "    # Vérifie les valeurs de X_train et X_test\n",
    "    print(\"X_train shape:\", X_train.shape)\n",
    "    print(\"X_test shape:\", X_test.shape)\n",
    "\n",
    "    # Compiler le modèle\n",
    "    model.compile(optimizer=optimizer(learning_rate=learning_rate),\n",
    "                  loss='categorical_crossentropy',\n",
    "                  metrics=['accuracy'])\n",
    "    \n",
    "    # Callbacks pour le modèle\n",
    "    early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)\n",
    "    reduce_lr = ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, min_lr=0.00001)\n",
    "    \n",
    "    # Entraîner le modèle\n",
    "    history = model.fit(X_train, y_train_cnn,\n",
    "                        validation_data=(X_test, y_test_cnn),\n",
    "                        callbacks=[early_stopping, reduce_lr],\n",
    "                        epochs=epochs)\n",
    "    \n",
    "    # Prédictions\n",
    "    predictions = model.predict(X_test)\n",
    "    y_pred = np.argmax(predictions, axis=1)\n",
    "    \n",
    "    # Évaluation du modèle\n",
    "    metrics_display(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Downloading data from https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_1.0_224_no_top.h5\n",
      "\u001b[1m9406464/9406464\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m0s\u001b[0m 0us/step\n"
     ]
    }
   ],
   "source": [
    "base_model = MobileNetV2(weights='imagenet',\n",
    "                         include_top=False,\n",
    "                         input_shape=(224, 224, 3))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "model = create_model(base_model, 3)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "brodcast_weights = sc.broadcast(model.get_weights())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "24/09/27 19:29:43 ERROR ClusterManager: Could not initialize cluster nodes=[cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal, cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal] nodeHostName=cluster-p8-m.europe-west1-b.c.eloquent-branch-436714-u0.internal nodeHostAddress=10.132.0.21 currentNodeIndex=null\n",
      "                                                                                \r"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "X_train shape: (1381, 224, 224, 3)\n",
      "X_test shape: (461, 224, 224, 3)\n",
      "Epoch 1/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m11s\u001b[0m 163ms/step - accuracy: 0.8937 - loss: 0.3220 - val_accuracy: 1.0000 - val_loss: 7.3474e-05 - learning_rate: 0.0010\n",
      "Epoch 2/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 130ms/step - accuracy: 1.0000 - loss: 1.2164e-05 - val_accuracy: 1.0000 - val_loss: 2.8806e-05 - learning_rate: 0.0010\n",
      "Epoch 3/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 130ms/step - accuracy: 1.0000 - loss: 5.3822e-06 - val_accuracy: 1.0000 - val_loss: 2.0219e-05 - learning_rate: 0.0010\n",
      "Epoch 4/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 136ms/step - accuracy: 1.0000 - loss: 3.4096e-06 - val_accuracy: 1.0000 - val_loss: 1.4014e-05 - learning_rate: 0.0010\n",
      "Epoch 5/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 135ms/step - accuracy: 1.0000 - loss: 2.4729e-06 - val_accuracy: 1.0000 - val_loss: 1.1974e-05 - learning_rate: 5.0000e-04\n",
      "Epoch 6/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 132ms/step - accuracy: 1.0000 - loss: 2.1122e-06 - val_accuracy: 1.0000 - val_loss: 1.0309e-05 - learning_rate: 5.0000e-04\n",
      "Epoch 7/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 130ms/step - accuracy: 1.0000 - loss: 1.8147e-06 - val_accuracy: 1.0000 - val_loss: 8.8970e-06 - learning_rate: 5.0000e-04\n",
      "Epoch 8/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 129ms/step - accuracy: 1.0000 - loss: 1.5906e-06 - val_accuracy: 1.0000 - val_loss: 8.2670e-06 - learning_rate: 2.5000e-04\n",
      "Epoch 9/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 128ms/step - accuracy: 1.0000 - loss: 1.4787e-06 - val_accuracy: 1.0000 - val_loss: 7.6922e-06 - learning_rate: 2.5000e-04\n",
      "Epoch 10/10\n",
      "\u001b[1m44/44\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m6s\u001b[0m 126ms/step - accuracy: 1.0000 - loss: 1.3738e-06 - val_accuracy: 1.0000 - val_loss: 7.1585e-06 - learning_rate: 2.5000e-04\n",
      "\u001b[1m15/15\u001b[0m \u001b[32m━━━━━━━━━━━━━━━━━━━━\u001b[0m\u001b[37m\u001b[0m \u001b[1m5s\u001b[0m 271ms/step\n",
      "accuracy = 1.0   precision = 1.0   recall=1.0   f1 = 1.0   ARI = 1.0\n"
     ]
    }
   ],
   "source": [
    "train_and_test_model_spark(train_dir, test_dir, model, spark)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "On peut observer que l'entraînement a été dix fois plus rapide qu'en local !"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### 3. Entraînement du modèle avec le dataset complet."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "train_dir = 'gs://chakir-p8/data/train'\n",
    "test_dir = 'gs://chakir-p8/data/test'"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\">Model: \"sequential_2\"</span>\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1mModel: \"sequential_2\"\u001b[0m\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\">┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓\n",
       "┃<span style=\"font-weight: bold\"> Layer (type)                    </span>┃<span style=\"font-weight: bold\"> Output Shape           </span>┃<span style=\"font-weight: bold\">       Param # </span>┃\n",
       "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩\n",
       "│ mobilenetv2_1.00_224            │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">7</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">7</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">1280</span>)     │     <span style=\"color: #00af00; text-decoration-color: #00af00\">2,257,984</span> │\n",
       "│ (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Functional</span>)                    │                        │               │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ global_average_pooling2d_2      │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">1280</span>)           │             <span style=\"color: #00af00; text-decoration-color: #00af00\">0</span> │\n",
       "│ (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">GlobalAveragePooling2D</span>)        │                        │               │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense_4 (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Dense</span>)                 │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">1024</span>)           │     <span style=\"color: #00af00; text-decoration-color: #00af00\">1,311,744</span> │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense_5 (<span style=\"color: #0087ff; text-decoration-color: #0087ff\">Dense</span>)                 │ (<span style=\"color: #00d7ff; text-decoration-color: #00d7ff\">None</span>, <span style=\"color: #00af00; text-decoration-color: #00af00\">131</span>)            │       <span style=\"color: #00af00; text-decoration-color: #00af00\">134,275</span> │\n",
       "└─────────────────────────────────┴────────────────────────┴───────────────┘\n",
       "</pre>\n"
      ],
      "text/plain": [
       "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓\n",
       "┃\u001b[1m \u001b[0m\u001b[1mLayer (type)                   \u001b[0m\u001b[1m \u001b[0m┃\u001b[1m \u001b[0m\u001b[1mOutput Shape          \u001b[0m\u001b[1m \u001b[0m┃\u001b[1m \u001b[0m\u001b[1m      Param #\u001b[0m\u001b[1m \u001b[0m┃\n",
       "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩\n",
       "│ mobilenetv2_1.00_224            │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m7\u001b[0m, \u001b[38;5;34m7\u001b[0m, \u001b[38;5;34m1280\u001b[0m)     │     \u001b[38;5;34m2,257,984\u001b[0m │\n",
       "│ (\u001b[38;5;33mFunctional\u001b[0m)                    │                        │               │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ global_average_pooling2d_2      │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m1280\u001b[0m)           │             \u001b[38;5;34m0\u001b[0m │\n",
       "│ (\u001b[38;5;33mGlobalAveragePooling2D\u001b[0m)        │                        │               │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense_4 (\u001b[38;5;33mDense\u001b[0m)                 │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m1024\u001b[0m)           │     \u001b[38;5;34m1,311,744\u001b[0m │\n",
       "├─────────────────────────────────┼────────────────────────┼───────────────┤\n",
       "│ dense_5 (\u001b[38;5;33mDense\u001b[0m)                 │ (\u001b[38;5;45mNone\u001b[0m, \u001b[38;5;34m131\u001b[0m)            │       \u001b[38;5;34m134,275\u001b[0m │\n",
       "└─────────────────────────────────┴────────────────────────┴───────────────┘\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\"> Total params: </span><span style=\"color: #00af00; text-decoration-color: #00af00\">3,704,003</span> (14.13 MB)\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1m Total params: \u001b[0m\u001b[38;5;34m3,704,003\u001b[0m (14.13 MB)\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\"> Trainable params: </span><span style=\"color: #00af00; text-decoration-color: #00af00\">1,446,019</span> (5.52 MB)\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1m Trainable params: \u001b[0m\u001b[38;5;34m1,446,019\u001b[0m (5.52 MB)\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-weight: bold\"> Non-trainable params: </span><span style=\"color: #00af00; text-decoration-color: #00af00\">2,257,984</span> (8.61 MB)\n",
       "</pre>\n"
      ],
      "text/plain": [
       "\u001b[1m Non-trainable params: \u001b[0m\u001b[38;5;34m2,257,984\u001b[0m (8.61 MB)\n"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "model = create_model(base_model, 131) # Il y a 131 classes de fruits\n",
    "model.summary()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [],
   "source": [
    "brodcast_weights = sc.broadcast(model.get_weights())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "24/09/27 19:59:33 WARN AsyncEventQueue: Dropped 22523 events from dataprocEvent since Fri Sep 27 19:48:14 UTC 2024.\n",
      "24/09/27 20:00:10 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:10 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 25 for reason Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:10 ERROR YarnScheduler: Lost executor 25 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:10 WARN TaskSetManager: Lost task 64.0 in stage 7.0 (TID 1566) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 25): ExecutorLostFailure (executor 25 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:10 WARN TaskSetManager: Lost task 66.0 in stage 7.0 (TID 1568) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 25): ExecutorLostFailure (executor 25 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:10 WARN TaskSetManager: Lost task 69.0 in stage 7.0 (TID 1571) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 25): ExecutorLostFailure (executor 25 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:10 WARN TaskSetManager: Lost task 68.0 in stage 7.0 (TID 1570) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 25): ExecutorLostFailure (executor 25 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000025 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:10.661]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:10.661]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:10.662]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 28 for reason Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 ERROR YarnScheduler: Lost executor 28 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 WARN TaskSetManager: Lost task 68.1 in stage 7.0 (TID 1578) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 28): ExecutorLostFailure (executor 28 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 WARN TaskSetManager: Lost task 64.1 in stage 7.0 (TID 1581) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 28): ExecutorLostFailure (executor 28 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 WARN TaskSetManager: Lost task 66.1 in stage 7.0 (TID 1580) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 28): ExecutorLostFailure (executor 28 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:16 WARN TaskSetManager: Lost task 69.1 in stage 7.0 (TID 1579) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 28): ExecutorLostFailure (executor 28 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000028 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:00:16.114]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:00:16.114]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:00:16.115]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 30 for reason Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 ERROR YarnScheduler: Lost executor 30 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 WARN TaskSetManager: Lost task 134.0 in stage 7.0 (TID 1644) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 30): ExecutorLostFailure (executor 30 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 WARN TaskSetManager: Lost task 133.0 in stage 7.0 (TID 1643) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 30): ExecutorLostFailure (executor 30 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 WARN TaskSetManager: Lost task 136.0 in stage 7.0 (TID 1646) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 30): ExecutorLostFailure (executor 30 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:00:48 WARN TaskSetManager: Lost task 132.0 in stage 7.0 (TID 1642) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 30): ExecutorLostFailure (executor 30 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000030 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:00:48.646]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:00:48.647]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:00:48.647]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 29 for reason Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 ERROR YarnScheduler: Lost executor 29 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 WARN TaskSetManager: Lost task 166.0 in stage 7.0 (TID 1680) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 29): ExecutorLostFailure (executor 29 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 WARN TaskSetManager: Lost task 165.0 in stage 7.0 (TID 1679) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 29): ExecutorLostFailure (executor 29 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 WARN TaskSetManager: Lost task 164.0 in stage 7.0 (TID 1678) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 29): ExecutorLostFailure (executor 29 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:05 WARN TaskSetManager: Lost task 167.0 in stage 7.0 (TID 1681) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 29): ExecutorLostFailure (executor 29 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000029 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:05.432]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:05.433]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:05.436]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 31 for reason Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 ERROR YarnScheduler: Lost executor 31 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 WARN TaskSetManager: Lost task 210.0 in stage 7.0 (TID 1728) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 31): ExecutorLostFailure (executor 31 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 WARN TaskSetManager: Lost task 209.0 in stage 7.0 (TID 1727) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 31): ExecutorLostFailure (executor 31 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 WARN TaskSetManager: Lost task 208.0 in stage 7.0 (TID 1726) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 31): ExecutorLostFailure (executor 31 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:28 WARN TaskSetManager: Lost task 211.0 in stage 7.0 (TID 1729) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 31): ExecutorLostFailure (executor 31 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000031 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:28.799]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:28.799]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:28.799]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 32 for reason Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 ERROR YarnScheduler: Lost executor 32 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 WARN TaskSetManager: Lost task 256.0 in stage 7.0 (TID 1778) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 32): ExecutorLostFailure (executor 32 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 WARN TaskSetManager: Lost task 258.0 in stage 7.0 (TID 1780) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 32): ExecutorLostFailure (executor 32 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 WARN TaskSetManager: Lost task 252.0 in stage 7.0 (TID 1774) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 32): ExecutorLostFailure (executor 32 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:01:53 WARN TaskSetManager: Lost task 254.0 in stage 7.0 (TID 1776) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 32): ExecutorLostFailure (executor 32 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000032 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:01:52.941]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:01:52.942]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:01:52.942]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 33 for reason Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 ERROR YarnScheduler: Lost executor 33 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 WARN TaskSetManager: Lost task 276.0 in stage 7.0 (TID 1802) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 33): ExecutorLostFailure (executor 33 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 WARN TaskSetManager: Lost task 279.0 in stage 7.0 (TID 1805) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 33): ExecutorLostFailure (executor 33 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 WARN TaskSetManager: Lost task 278.0 in stage 7.0 (TID 1804) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 33): ExecutorLostFailure (executor 33 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:04 WARN TaskSetManager: Lost task 277.0 in stage 7.0 (TID 1803) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 33): ExecutorLostFailure (executor 33 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000033 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:04.529]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:04.530]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:04.530]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 34 for reason Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 ERROR YarnScheduler: Lost executor 34 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 WARN TaskSetManager: Lost task 350.0 in stage 7.0 (TID 1880) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 34): ExecutorLostFailure (executor 34 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 WARN TaskSetManager: Lost task 343.0 in stage 7.0 (TID 1873) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 34): ExecutorLostFailure (executor 34 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 WARN TaskSetManager: Lost task 346.0 in stage 7.0 (TID 1876) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 34): ExecutorLostFailure (executor 34 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:39 WARN TaskSetManager: Lost task 348.0 in stage 7.0 (TID 1878) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 34): ExecutorLostFailure (executor 34 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000034 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:38.883]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:38.884]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:38.884]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 35 for reason Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 ERROR YarnScheduler: Lost executor 35 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 WARN TaskSetManager: Lost task 352.0 in stage 7.0 (TID 1886) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 35): ExecutorLostFailure (executor 35 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 WARN TaskSetManager: Lost task 355.0 in stage 7.0 (TID 1889) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 35): ExecutorLostFailure (executor 35 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 WARN TaskSetManager: Lost task 354.0 in stage 7.0 (TID 1888) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 35): ExecutorLostFailure (executor 35 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:02:44 WARN TaskSetManager: Lost task 353.0 in stage 7.0 (TID 1887) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 35): ExecutorLostFailure (executor 35 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000035 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:02:44.120]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:02:44.120]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:02:44.121]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 36 for reason Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 ERROR YarnScheduler: Lost executor 36 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 WARN TaskSetManager: Lost task 423.0 in stage 7.0 (TID 1961) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 36): ExecutorLostFailure (executor 36 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 WARN TaskSetManager: Lost task 420.0 in stage 7.0 (TID 1958) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 36): ExecutorLostFailure (executor 36 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 WARN TaskSetManager: Lost task 422.0 in stage 7.0 (TID 1960) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 36): ExecutorLostFailure (executor 36 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:20 WARN TaskSetManager: Lost task 421.0 in stage 7.0 (TID 1959) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 36): ExecutorLostFailure (executor 36 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000036 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:20.210]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:20.210]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:20.211]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 37 for reason Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 ERROR YarnScheduler: Lost executor 37 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 WARN TaskSetManager: Lost task 426.0 in stage 7.0 (TID 1964) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 37): ExecutorLostFailure (executor 37 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 WARN TaskSetManager: Lost task 425.0 in stage 7.0 (TID 1963) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 37): ExecutorLostFailure (executor 37 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 WARN TaskSetManager: Lost task 427.0 in stage 7.0 (TID 1965) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 37): ExecutorLostFailure (executor 37 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:22 WARN TaskSetManager: Lost task 424.0 in stage 7.0 (TID 1962) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 37): ExecutorLostFailure (executor 37 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000037 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:21.937]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:21.937]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:21.939]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 39 for reason Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 ERROR YarnScheduler: Lost executor 39 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 WARN TaskSetManager: Lost task 484.0 in stage 7.0 (TID 2030) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 39): ExecutorLostFailure (executor 39 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 WARN TaskSetManager: Lost task 487.0 in stage 7.0 (TID 2033) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 39): ExecutorLostFailure (executor 39 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 WARN TaskSetManager: Lost task 486.0 in stage 7.0 (TID 2032) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 39): ExecutorLostFailure (executor 39 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:03:56 WARN TaskSetManager: Lost task 485.0 in stage 7.0 (TID 2031) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 39): ExecutorLostFailure (executor 39 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000039 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:03:55.961]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:03:55.961]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:03:55.962]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 38 for reason Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 ERROR YarnScheduler: Lost executor 38 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 WARN TaskSetManager: Lost task 507.0 in stage 7.0 (TID 2057) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 38): ExecutorLostFailure (executor 38 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 WARN TaskSetManager: Lost task 501.0 in stage 7.0 (TID 2051) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 38): ExecutorLostFailure (executor 38 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 WARN TaskSetManager: Lost task 500.0 in stage 7.0 (TID 2050) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 38): ExecutorLostFailure (executor 38 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:04 WARN TaskSetManager: Lost task 502.0 in stage 7.0 (TID 2052) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 38): ExecutorLostFailure (executor 38 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000038 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:04.571]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:04.572]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:04.572]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 41 for reason Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 ERROR YarnScheduler: Lost executor 41 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 WARN TaskSetManager: Lost task 566.0 in stage 7.0 (TID 2120) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 41): ExecutorLostFailure (executor 41 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 WARN TaskSetManager: Lost task 565.0 in stage 7.0 (TID 2119) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 41): ExecutorLostFailure (executor 41 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 WARN TaskSetManager: Lost task 564.0 in stage 7.0 (TID 2118) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 41): ExecutorLostFailure (executor 41 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:40 WARN TaskSetManager: Lost task 567.0 in stage 7.0 (TID 2121) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 41): ExecutorLostFailure (executor 41 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000041 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 143. Diagnostics: [2024-09-27 20:04:40.190]Container killed on request. Exit code is 143\n",
      "[2024-09-27 20:04:40.190]Container exited with a non-zero exit code 143. \n",
      "[2024-09-27 20:04:40.191]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 40 for reason Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 ERROR YarnScheduler: Lost executor 40 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 WARN TaskSetManager: Lost task 598.0 in stage 7.0 (TID 2156) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 40): ExecutorLostFailure (executor 40 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 WARN TaskSetManager: Lost task 597.0 in stage 7.0 (TID 2155) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 40): ExecutorLostFailure (executor 40 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 WARN TaskSetManager: Lost task 596.0 in stage 7.0 (TID 2154) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 40): ExecutorLostFailure (executor 40 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:04:55 WARN TaskSetManager: Lost task 599.0 in stage 7.0 (TID 2157) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 40): ExecutorLostFailure (executor 40 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000040 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:04:55.790]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:04:55.790]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:04:55.791]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 42 for reason Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 ERROR YarnScheduler: Lost executor 42 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 WARN TaskSetManager: Lost task 641.0 in stage 7.0 (TID 2203) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 42): ExecutorLostFailure (executor 42 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 WARN TaskSetManager: Lost task 643.0 in stage 7.0 (TID 2205) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 42): ExecutorLostFailure (executor 42 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 WARN TaskSetManager: Lost task 640.0 in stage 7.0 (TID 2202) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 42): ExecutorLostFailure (executor 42 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:20 WARN TaskSetManager: Lost task 642.0 in stage 7.0 (TID 2204) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 42): ExecutorLostFailure (executor 42 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000042 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:19.984]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:19.984]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:19.984]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 43 for reason Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 ERROR YarnScheduler: Lost executor 43 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 WARN TaskSetManager: Lost task 670.0 in stage 7.0 (TID 2236) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 43): ExecutorLostFailure (executor 43 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 WARN TaskSetManager: Lost task 669.0 in stage 7.0 (TID 2235) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 43): ExecutorLostFailure (executor 43 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 WARN TaskSetManager: Lost task 668.0 in stage 7.0 (TID 2234) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 43): ExecutorLostFailure (executor 43 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:05:37 WARN TaskSetManager: Lost task 671.0 in stage 7.0 (TID 2237) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 43): ExecutorLostFailure (executor 43 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000043 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:05:36.938]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:05:36.938]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:05:36.940]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 44 for reason Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 ERROR YarnScheduler: Lost executor 44 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 WARN TaskSetManager: Lost task 714.0 in stage 7.0 (TID 2284) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 44): ExecutorLostFailure (executor 44 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 WARN TaskSetManager: Lost task 711.0 in stage 7.0 (TID 2281) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 44): ExecutorLostFailure (executor 44 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 WARN TaskSetManager: Lost task 713.0 in stage 7.0 (TID 2283) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 44): ExecutorLostFailure (executor 44 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:01 WARN TaskSetManager: Lost task 715.0 in stage 7.0 (TID 2285) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 44): ExecutorLostFailure (executor 44 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000044 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:01.598]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:01.598]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:01.599]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 45 for reason Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 ERROR YarnScheduler: Lost executor 45 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 WARN TaskSetManager: Lost task 746.0 in stage 7.0 (TID 2320) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 45): ExecutorLostFailure (executor 45 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 WARN TaskSetManager: Lost task 745.0 in stage 7.0 (TID 2319) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 45): ExecutorLostFailure (executor 45 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 WARN TaskSetManager: Lost task 748.0 in stage 7.0 (TID 2322) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 45): ExecutorLostFailure (executor 45 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:26 WARN TaskSetManager: Lost task 747.0 in stage 7.0 (TID 2321) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 45): ExecutorLostFailure (executor 45 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000045 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:26.101]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:26.102]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:26.102]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 46 for reason Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 ERROR YarnScheduler: Lost executor 46 on cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 WARN TaskSetManager: Lost task 798.0 in stage 7.0 (TID 2376) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 46): ExecutorLostFailure (executor 46 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 WARN TaskSetManager: Lost task 792.0 in stage 7.0 (TID 2370) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 46): ExecutorLostFailure (executor 46 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 WARN TaskSetManager: Lost task 797.0 in stage 7.0 (TID 2375) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 46): ExecutorLostFailure (executor 46 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:06:53 WARN TaskSetManager: Lost task 799.0 in stage 7.0 (TID 2377) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 46): ExecutorLostFailure (executor 46 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000046 on host: cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:06:53.261]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:06:53.261]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:06:53.262]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 WARN YarnAllocator: Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 WARN YarnSchedulerBackend$YarnSchedulerEndpoint: Requesting driver to remove executor 47 for reason Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 ERROR YarnScheduler: Lost executor 47 on cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal: Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 837.0 in stage 7.0 (TID 2419) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 47): ExecutorLostFailure (executor 47 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 836.0 in stage 7.0 (TID 2418) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 47): ExecutorLostFailure (executor 47 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 839.0 in stage 7.0 (TID 2421) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 47): ExecutorLostFailure (executor 47 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 838.0 in stage 7.0 (TID 2420) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 47): ExecutorLostFailure (executor 47 exited caused by one of the running tasks) Reason: Container from a bad node: container_1727464744947_0001_01_000047 on host: cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal. Exit status: 137. Diagnostics: [2024-09-27 20:07:19.287]Container killed on request. Exit code is 137\n",
      "[2024-09-27 20:07:19.288]Container exited with a non-zero exit code 137. \n",
      "[2024-09-27 20:07:19.289]Killed by external signal\n",
      ".\n",
      "24/09/27 20:07:19 ERROR TaskSetManager: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB)\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 828.0 in stage 7.0 (TID 2410) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 49): TaskKilled (Tasks result size has exceeded maxResultSize)\n",
      "24/09/27 20:07:19 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:19 ERROR TaskSetManager: Total size of serialized results of 827 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB)\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 831.0 in stage 7.0 (TID 2413) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 49): TaskKilled (Tasks result size has exceeded maxResultSize)\n",
      "24/09/27 20:07:19 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 839.1 in stage 7.0 (TID 2423) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 49): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:19 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 829.0 in stage 7.0 (TID 2411) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 49): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:19 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n"
     ]
    },
    {
     "ename": "Py4JJavaError",
     "evalue": "An error occurred while calling o201.collectToPython.\n: org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB)\n\tat org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)\n\tat scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)\n\tat scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)\n\tat scala.Option.foreach(Option.scala:407)\n\tat org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)\n\tat org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2449)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2470)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2489)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2514)\n\tat org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1049)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)\n\tat org.apache.spark.rdd.RDD.withScope(RDD.scala:410)\n\tat org.apache.spark.rdd.RDD.collect(RDD.scala:1048)\n\tat org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:448)\n\tat org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:4148)\n\tat org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4322)\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:547)\n\tat org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4320)\n\tat org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)\n\tat org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)\n\tat org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)\n\tat org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)\n\tat org.apache.spark.sql.Dataset.withAction(Dataset.scala:4320)\n\tat org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4145)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:106)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mPy4JJavaError\u001b[0m                             Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[23], line 1\u001b[0m\n\u001b[0;32m----> 1\u001b[0m \u001b[43mtrain_and_test_model_spark\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrain_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtest_dir\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mmodel\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mspark\u001b[49m\u001b[43m)\u001b[49m\n",
      "Cell \u001b[0;32mIn[10], line 23\u001b[0m, in \u001b[0;36mtrain_and_test_model_spark\u001b[0;34m(train_dir, test_dir, model, spark_session, seed_value, target_size, optimizer, learning_rate, epochs)\u001b[0m\n\u001b[1;32m     20\u001b[0m test_df \u001b[38;5;241m=\u001b[39m test_df\u001b[38;5;241m.\u001b[39mwithColumn(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpreprocessed_image\u001b[39m\u001b[38;5;124m'\u001b[39m, preprocess_image_udf(col(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mcontent\u001b[39m\u001b[38;5;124m'\u001b[39m)))\n\u001b[1;32m     22\u001b[0m \u001b[38;5;66;03m# Conversion en format numpy pour le modèle tensorflow\u001b[39;00m\n\u001b[0;32m---> 23\u001b[0m train_data \u001b[38;5;241m=\u001b[39m \u001b[43mtrain_df\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mselect\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mpreprocessed_image\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[38;5;124;43mlabel\u001b[39;49m\u001b[38;5;124;43m'\u001b[39;49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcollect\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m     24\u001b[0m test_data \u001b[38;5;241m=\u001b[39m test_df\u001b[38;5;241m.\u001b[39mselect(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpreprocessed_image\u001b[39m\u001b[38;5;124m'\u001b[39m, \u001b[38;5;124m'\u001b[39m\u001b[38;5;124mlabel\u001b[39m\u001b[38;5;124m'\u001b[39m)\u001b[38;5;241m.\u001b[39mcollect()\n\u001b[1;32m     26\u001b[0m X_train \u001b[38;5;241m=\u001b[39m np\u001b[38;5;241m.\u001b[39marray([np\u001b[38;5;241m.\u001b[39marray(row[\u001b[38;5;124m'\u001b[39m\u001b[38;5;124mpreprocessed_image\u001b[39m\u001b[38;5;124m'\u001b[39m])\u001b[38;5;241m.\u001b[39mreshape(\u001b[38;5;241m224\u001b[39m, \u001b[38;5;241m224\u001b[39m, \u001b[38;5;241m3\u001b[39m) \u001b[38;5;28;01mfor\u001b[39;00m row \u001b[38;5;129;01min\u001b[39;00m train_data])\n",
      "File \u001b[0;32m/usr/lib/spark/python/pyspark/sql/dataframe.py:1261\u001b[0m, in \u001b[0;36mDataFrame.collect\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m   1241\u001b[0m \u001b[38;5;250m\u001b[39m\u001b[38;5;124;03m\"\"\"Returns all the records as a list of :class:`Row`.\u001b[39;00m\n\u001b[1;32m   1242\u001b[0m \n\u001b[1;32m   1243\u001b[0m \u001b[38;5;124;03m.. versionadded:: 1.3.0\u001b[39;00m\n\u001b[0;32m   (...)\u001b[0m\n\u001b[1;32m   1258\u001b[0m \u001b[38;5;124;03m[Row(age=14, name='Tom'), Row(age=23, name='Alice'), Row(age=16, name='Bob')]\u001b[39;00m\n\u001b[1;32m   1259\u001b[0m \u001b[38;5;124;03m\"\"\"\u001b[39;00m\n\u001b[1;32m   1260\u001b[0m \u001b[38;5;28;01mwith\u001b[39;00m SCCallSiteSync(\u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_sc):\n\u001b[0;32m-> 1261\u001b[0m     sock_info \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_jdf\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mcollectToPython\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1262\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28mlist\u001b[39m(_load_from_socket(sock_info, BatchedSerializer(CPickleSerializer())))\n",
      "File \u001b[0;32m/opt/conda/miniconda3/lib/python3.11/site-packages/py4j/java_gateway.py:1322\u001b[0m, in \u001b[0;36mJavaMember.__call__\u001b[0;34m(self, *args)\u001b[0m\n\u001b[1;32m   1316\u001b[0m command \u001b[38;5;241m=\u001b[39m proto\u001b[38;5;241m.\u001b[39mCALL_COMMAND_NAME \u001b[38;5;241m+\u001b[39m\\\n\u001b[1;32m   1317\u001b[0m     \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mcommand_header \u001b[38;5;241m+\u001b[39m\\\n\u001b[1;32m   1318\u001b[0m     args_command \u001b[38;5;241m+\u001b[39m\\\n\u001b[1;32m   1319\u001b[0m     proto\u001b[38;5;241m.\u001b[39mEND_COMMAND_PART\n\u001b[1;32m   1321\u001b[0m answer \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mgateway_client\u001b[38;5;241m.\u001b[39msend_command(command)\n\u001b[0;32m-> 1322\u001b[0m return_value \u001b[38;5;241m=\u001b[39m \u001b[43mget_return_value\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m   1323\u001b[0m \u001b[43m    \u001b[49m\u001b[43manswer\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mgateway_client\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mtarget_id\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mname\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m   1325\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m temp_arg \u001b[38;5;129;01min\u001b[39;00m temp_args:\n\u001b[1;32m   1326\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mhasattr\u001b[39m(temp_arg, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m_detach\u001b[39m\u001b[38;5;124m\"\u001b[39m):\n",
      "File \u001b[0;32m/usr/lib/spark/python/pyspark/errors/exceptions/captured.py:179\u001b[0m, in \u001b[0;36mcapture_sql_exception.<locals>.deco\u001b[0;34m(*a, **kw)\u001b[0m\n\u001b[1;32m    177\u001b[0m \u001b[38;5;28;01mdef\u001b[39;00m \u001b[38;5;21mdeco\u001b[39m(\u001b[38;5;241m*\u001b[39ma: Any, \u001b[38;5;241m*\u001b[39m\u001b[38;5;241m*\u001b[39mkw: Any) \u001b[38;5;241m-\u001b[39m\u001b[38;5;241m>\u001b[39m Any:\n\u001b[1;32m    178\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 179\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mf\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43ma\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkw\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    180\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m Py4JJavaError \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    181\u001b[0m         converted \u001b[38;5;241m=\u001b[39m convert_exception(e\u001b[38;5;241m.\u001b[39mjava_exception)\n",
      "File \u001b[0;32m/opt/conda/miniconda3/lib/python3.11/site-packages/py4j/protocol.py:326\u001b[0m, in \u001b[0;36mget_return_value\u001b[0;34m(answer, gateway_client, target_id, name)\u001b[0m\n\u001b[1;32m    324\u001b[0m value \u001b[38;5;241m=\u001b[39m OUTPUT_CONVERTER[\u001b[38;5;28mtype\u001b[39m](answer[\u001b[38;5;241m2\u001b[39m:], gateway_client)\n\u001b[1;32m    325\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m answer[\u001b[38;5;241m1\u001b[39m] \u001b[38;5;241m==\u001b[39m REFERENCE_TYPE:\n\u001b[0;32m--> 326\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m Py4JJavaError(\n\u001b[1;32m    327\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAn error occurred while calling \u001b[39m\u001b[38;5;132;01m{0}\u001b[39;00m\u001b[38;5;132;01m{1}\u001b[39;00m\u001b[38;5;132;01m{2}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39m\n\u001b[1;32m    328\u001b[0m         \u001b[38;5;28mformat\u001b[39m(target_id, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m\"\u001b[39m, name), value)\n\u001b[1;32m    329\u001b[0m \u001b[38;5;28;01melse\u001b[39;00m:\n\u001b[1;32m    330\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m Py4JError(\n\u001b[1;32m    331\u001b[0m         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mAn error occurred while calling \u001b[39m\u001b[38;5;132;01m{0}\u001b[39;00m\u001b[38;5;132;01m{1}\u001b[39;00m\u001b[38;5;132;01m{2}\u001b[39;00m\u001b[38;5;124m. Trace:\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;132;01m{3}\u001b[39;00m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;241m.\u001b[39m\n\u001b[1;32m    332\u001b[0m         \u001b[38;5;28mformat\u001b[39m(target_id, \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m.\u001b[39m\u001b[38;5;124m\"\u001b[39m, name, value))\n",
      "\u001b[0;31mPy4JJavaError\u001b[0m: An error occurred while calling o201.collectToPython.\n: org.apache.spark.SparkException: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB)\n\tat org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)\n\tat scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)\n\tat scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)\n\tat scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)\n\tat org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)\n\tat scala.Option.foreach(Option.scala:407)\n\tat org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)\n\tat org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)\n\tat org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)\n\tat org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2449)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2470)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2489)\n\tat org.apache.spark.SparkContext.runJob(SparkContext.scala:2514)\n\tat org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1049)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)\n\tat org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)\n\tat org.apache.spark.rdd.RDD.withScope(RDD.scala:410)\n\tat org.apache.spark.rdd.RDD.collect(RDD.scala:1048)\n\tat org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:448)\n\tat org.apache.spark.sql.Dataset.$anonfun$collectToPython$1(Dataset.scala:4148)\n\tat org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4322)\n\tat org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:547)\n\tat org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4320)\n\tat org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)\n\tat org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)\n\tat org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)\n\tat org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)\n\tat org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)\n\tat org.apache.spark.sql.Dataset.withAction(Dataset.scala:4320)\n\tat org.apache.spark.sql.Dataset.collectToPython(Dataset.scala:4145)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)\n\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)\n\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:566)\n\tat py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)\n\tat py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)\n\tat py4j.Gateway.invoke(Gateway.java:282)\n\tat py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)\n\tat py4j.commands.CallCommand.execute(CallCommand.java:79)\n\tat py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)\n\tat py4j.ClientServerConnection.run(ClientServerConnection.java:106)\n\tat java.base/java.lang.Thread.run(Thread.java:829)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "24/09/27 20:07:19 WARN TaskSetManager: Lost task 838.1 in stage 7.0 (TID 2422) (cluster-p8-w-1.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 49): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:19 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:20 WARN TaskSetManager: Lost task 813.0 in stage 7.0 (TID 2395) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 50): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:20 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:20 WARN TaskSetManager: Lost task 814.0 in stage 7.0 (TID 2396) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 50): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:20 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:20 WARN TaskSetManager: Lost task 832.0 in stage 7.0 (TID 2414) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 48): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:20 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:20 WARN TaskSetManager: Lost task 816.0 in stage 7.0 (TID 2398) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 50): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:20 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:21 WARN TaskSetManager: Lost task 815.0 in stage 7.0 (TID 2397) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 50): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:21 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:21 WARN TaskSetManager: Lost task 833.0 in stage 7.0 (TID 2415) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 48): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:21 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:21 WARN TaskSetManager: Lost task 834.0 in stage 7.0 (TID 2416) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 48): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:21 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "24/09/27 20:07:21 WARN TaskSetManager: Lost task 835.0 in stage 7.0 (TID 2417) (cluster-p8-w-0.europe-west1-b.c.eloquent-branch-436714-u0.internal executor 48): TaskKilled (Stage cancelled: Job aborted due to stage failure: Total size of serialized results of 826 tasks (8.0 GiB) is bigger than spark.driver.maxResultSize (8.0 GiB))\n",
      "24/09/27 20:07:21 ERROR AsyncEventQueue: Listener ExecutorAllocationListener threw an exception\n",
      "java.util.NoSuchElementException: key not found: Stage 7 (Attempt 0)\n",
      "\tat scala.collection.MapLike.default(MapLike.scala:236) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.MapLike.default$(MapLike.scala:235) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.AbstractMap.default(Map.scala:65) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.collection.mutable.HashMap.apply(HashMap.scala:69) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.ExecutorAllocationManager$ExecutorAllocationListener.onTaskEnd(ExecutorAllocationManager.scala:837) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:45) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23) ~[scala-library-2.12.18.jar:?]\n",
      "\tat scala.util.DynamicVariable.withValue(DynamicVariable.scala:62) ~[scala-library-2.12.18.jar:?]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96) ~[spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1357) [spark-core_2.12-3.5.1.jar:3.5.1]\n",
      "\tat org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96) [spark-core_2.12-3.5.1.jar:3.5.1]\n"
     ]
    }
   ],
   "source": [
    "train_and_test_model_spark(train_dir, test_dir, model, spark)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "base",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
